#!/bin/bash
# Author: Michael Claybaugh
# Date created: Friday, Apr 13, 2018
# Description: Bash shell script for automating the setup of my prefered linux
#              programs and settings

# 1. Create separate home partition
# 2. Install linux
# 3. install software

#**************************************************************
# Section 1: Installation of software
#**************************************************************

installNorms() {
	apt install build-essential zsh curl git htop npm nodejs ranger \
		fonts-powerline
}
echo "apt install build-essential zsh curl git htop npm nodejs ranger fonts-powerline"
read -p "Install normal stuff? [y/N]: " installNorm
if [ "$installNorm" == "y" ]; then
	installNorms
fi

installPython() {
	apt install python python-dev python-pip python3 python3-dev python3-pip
}
echo "apt install python python-dev python-pip python3 python3-dev python3-pip"
read -p "Install python? [y/N]: " installPython
if [ "$installPython" == "y" ]; then
	installPython
fi

# Python
#apt install python python-dev python-pip python3 python3-dev python3-pip

# Docker
#apt install docker docker-compose

# PHP
#apt install php

# Latex
#texlive-full biber

# OTHER
# Visual Studio Code, Google Chrome
#npm install -g eslint

# zsh, ohmyz.sh
#chsh -s $(which zsh)
# Then logout and back in
#sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Vim-Plug
#   2. Open vim, install plugins with ":PlugInstall"

#*************************************************************
# Section 2: post install
#**************************************************************

#*************************************************************
# Section 3: Updating config files in home directory
#**************************************************************
#TARGET_USER="mclaybaugh2"

# Setup git
#git config --global user.name "Michael Claybaugh"
#git config --global user.email "mclaybaugh2@liberty.edu"

# Unused files, do not comment unless using these
#cp ./.config/i3/config "/home/$TARGET_USER/.config/i3/config" -v
