#!/bin/sh
# Author: Michael Claybaugh
# Description: Shell script for automating the setup of my prefered linux
#              programs and settings

# To connect to SQL Server
#sudo apt install freetds unixodbc unixodbc-dev

installNorms() {
  # git info setup
  git config --global user.name "Michael Claybaugh"
  git config --global user.email "michael.claybaugh@gmail.com"

  # bash setup
  git clone https://github.com/magicmonty/bash-git-prompt ../bash-git-prompt

  # vim-plug
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  echo "After this setup, open vim and type :PlugInstall"
}

installUbuntuNorms() {
  # general
  sudo apt install build-essential curl wget ranger

  # javascript dev
  sudo apt install npm nodejs

  # docker
  sudo apt install docker docker-compose

  # linting
  sudo apt install php shellcheck
  sudo npm install --global eslint

  # smb
  sudo apt install cifs-utils

  # neovim
  sudo apt install neovim

  # vim copy/paste, ctags
  sudo apt install xclip universal-ctags

  installNorms
}

installMacNorms() {
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install ranger wget shellcheck nodejs neovim
  installNorms
}

cloneBuildNeovim() {
  echo "SETUP: Install prerequisites..."
  sudo apt install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip
  echo "SETUP: Clone repository..."
  git clone https://github.com/neovim/neovim ../neovim
  echo "SETUP: Build and install..."
  cd ../neovim || exit
  make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/neovim" CMAKE_BUILD_TYPE=Release
  make install
  cd ../linux-setup || exit
}

copyConfigs() {
  REPO_HOME="$HOME/repositories/linux-setup"
  VIM_CONFIG_DIR=~/.config/nvim
  cp -v "$REPO_HOME/config/bashrc" "$HOME/.bashrc"
  cp -v "$REPO_HOME/config/git-prompt-colors.sh" "$HOME/.git-prompt-colors.sh"
  cp -v "$REPO_HOME/config/eslintrc.json" "$HOME/.eslintrc.json"
  if [ ! -d "$VIM_CONFIG_DIR" ]; then
    mkdir -p $VIM_CONFIG_DIR
  fi
  cp -v "$REPO_HOME/config/vimrc" "$VIM_CONFIG_DIR/init.vim"
}

sshFolderPerms() {
  sudo chmod -v 700 ~/.ssh
  sudo chmod -v 644 ~/.ssh/*.pub
  sudo chmod -v 600 ~/.ssh/*.id_rsa
  sudo chmod -v 600 ~/.ssh/config
}

showCommands() {
  echo ""
  echo "Available commands:"
  echo "    ubuntu, mac, neovim, configs, sshPerms, exit"
  echo ""
}

TASK="start"
if [ "$1" = 'configs' ]; then
  copyConfigs
exit 0
fi

echo "Setup by Michael Claybaugh, type 'help' for available commands or 'exit' to quit";

while [ "$TASK" != "exit" ]; do
  printf "SETUP> "
  read -r TASK

  case $TASK in
    "exit")
      echo "Peace out";;
    "ubuntu")
      installUbuntuNorms;;
    "mac")
      installMacNorms;;
    "neovim")
      cloneBuildNeovim;;
    "configs")
      copyConfigs;;
    "sshPerms")
      sshFolderPerms;;
    "help")
      showCommands;;
    *)
      echo "Invalid option"
  esac
done
