#!/bin/bash
# Syncing files in ~/Backup/ to personal server

LOCAL="$HOME/Backup/"
REMOTE="michael@michaelclaybaugh.com:Backup/"

check_backup_status () {
	rsync --recursive --verbose --times --human-readable  --update --dry-run \
		--exclude-from="exclude.txt" \
		$LOCAL $REMOTE
}

check_pull_status () {
	rsync --recursive --verbose --times --human-readable --update --dry-run  \
		--exclude-from="exclude.txt" \
		$REMOTE $LOCAL
}

backup_files () {
	rsync --recursive --verbose --times --human-readable \
		--exclude-from="exclude.txt" \
		$LOCAL $REMOTE
}

backupAndDeleteDest_files () {
	rsync --recursive --verbose --times --human-readable --delete \
		--exclude-from="exclude.txt" \
		$LOCAL $REMOTE
}

pull_files () {
	rsync --recursive --verbose --times --human-readable \
		--exclude-from="exclude.txt" \
		$REMOTE $LOCAL
}


read -p "Check pull status? [y/n]: " checkSync
if [ "$checkSync" == "y" ]; then
	check_pull_status
fi

read -p "Check backup status? [y/n]: " checkBackup
if [ "$checkBackup" == "y" ]; then
		check_backup_status
fi

read -p "Pull files? [y/n]: " pull
if [ "$pull" == "y" ]; then
	pull_files
fi

read -p "Backup files? [y/n]: " backup
if [ "$backup" == "y" ]; then
	read -p "Delete other DEST files? [y/n]: " delete
	if [ "$delete" == "y" ]; then
		backupAndDeleteDest_files
	else
		backup_files
	fi
fi
